### ISSUE TITLE
微信7.0无法分享多张图片，分享单图可以成功

### ISSUE THREAD

**Issue by ryanypm** [kmlidc/react-native-share-local#24]
如果可以想在pictures加一个参数控制是否分享多张，提一个pull request。

作者有更好的解决方案么？

**Comment by git-Asir** [comment]
请问微信7.0 android 分享朋友圈正常吗？
我这总是提示 “获取资源失败，无法分享至朋友圈”

**Comment by ryanypm** [comment]
> 请问微信7.0 android分享朋友圈正常吗？
> 我这总是提示“获取资源失败，无法分享至朋友圈”

不能分享多图， 只能分享一张图片，需要改源码才行
这是我改的
![image](https://user-images.githubusercontent.com/7519919/51251938-739e6680-19d5-11e9-9615-a8b1a6e98eda.png)

https://github.com/ryanypm/react-native-share-local

**Comment by kmlidc** [comment]
已经修改好 提交了
