### ISSUE TITLE
可以增加ios 的特定分享平台么？

### ISSUE THREAD

**Issue by banli17** [kmlidc/react-native-share-local#7]
现在我是通过新增了一个库实现的。方法如下：

```
 NSString *test = @"com.tencent.xin.sharetimeline";
  NSUInteger count = [ImagesUrl count];
  //定义一个可变数组来存放分享的图片，最多不能超过9个
  NSMutableArray * objectsToShare = [NSMutableArray arrayWithCapacity:9];
  
  SLComposeViewController *activityVC = [SLComposeViewController composeViewControllerForServiceType:test];
  for (int i = 0; i < count; i++) {
    NSString * imageUrl = [ImagesUrl objectAtIndex: i];
    UIImage * imageToShare = [UIImage imageWithData:[NSData dataWithContentsOfURL:[NSURL URLWithString: imageUrl]]];
    [objectsToShare addObject:imageToShare];
    [activityVC addImage:imageToShare];
    if(i == 8)break;
```

可以新增到这个库里面吗，谢谢大神。

希望和android一样，搞成这样：
```
sharePictures({
	component : ["com.tencent.xin.sharetimeline"],
	imagesUrl,
});
```

**Comment by kmlidc** [comment]
可以的，加我QQ476004100

**Comment by xdkaka** [comment]
@hongshu123 这个我直接加到代码中会报错，是不是还要其他操作 貌似这个变量没有定义  多谢了
![qq20170930-161539](https://user-images.githubusercontent.com/3340436/31044106-64b047c2-a58e-11e7-8b3e-cbd50be80904.png)
![qq20170930-161600](https://user-images.githubusercontent.com/3340436/31044107-68588452-a58e-11e7-8b40-0630d5c4e120.png)

**Comment by xdkaka** [comment]
@hongshu123 这个我直接加到代码中会报错，是不是还要其他操作 貌似这个变量没有定义 多谢了
![qq20170930-161539](https://user-images.githubusercontent.com/3340436/31044121-cf8aeeb2-a58e-11e7-89ab-f269fb9395c3.png)
![22](https://user-images.githubusercontent.com/3340436/31044122-d19b01d8-a58e-11e7-92ea-cc7de050aaf6.png)

**Comment by banli17** [comment]
@xdkaka   如下图
<img width="988" alt="1" src="https://user-images.githubusercontent.com/12556069/31044172-e5c77a1e-a58f-11e7-8553-1235509f6108.png">

<img width="733" alt="2" src="https://user-images.githubusercontent.com/12556069/31044191-304d6df0-a590-11e7-821d-2ee2d04d705a.png">

**Comment by xdkaka** [comment]
@hongshu123  
非常感谢，虽然不懂ios代码，但是依葫芦画瓢又加上了自定义component分享到qq
![a](https://user-images.githubusercontent.com/3340436/31052353-01bf08dc-a648-11e7-9147-eee8fd1e5e32.png)
![b](https://user-images.githubusercontent.com/3340436/31052354-01c2e1b4-a648-11e7-9d99-3300107e731e.png)
![c](https://user-images.githubusercontent.com/3340436/31052355-01e8eb66-a648-11e7-9e53-c025235bc5e0.png)

**Comment by kmlidc** [comment]
@hongshu123 你这个不支持ios11吧

**Comment by kmlidc** [comment]
IOS11目前不支持指定分享了

**Comment by banli17** [comment]
是滴 ios 11不支持指定分享了，我刚刚把指定微信分享去掉了。
